import type { PayMethod } from "../data";

/* everything the invoice document needs — both the checkout receipt
   and the cart panel can build one of these from what they have */
export type InvoiceData = {
  txid: string;
  product: string;
  tag: string;
  price: number;
  method: PayMethod;
  methodDetail: string;
  customer: string;
  date: string;
};

const esc = (s: string) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

function invoiceHtml(inv: InvoiceData) {
  const rows = [
    ["Invoice no.", `INV-${inv.txid.replace(/^AXZ-/, "")}`],
    ["Transaction ID", inv.txid],
    ["Date", inv.date],
    ["Billed to", inv.customer],
    ["Payment method", `${inv.method} — ${inv.methodDetail}`],
  ]
    .map(
      ([k, v]) =>
        `<div class="row"><span class="k">${esc(k)}</span><span class="v">${esc(v)}</span></div>`
    )
    .join("");

  return `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>Invoice ${esc(inv.txid)} — AXZY</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: "Plus Jakarta Sans", system-ui, -apple-system, sans-serif;
    color: #101012;
    background: #fff;
    padding: 48px;
  }
  .sheet { max-width: 640px; margin: 0 auto; }
  .head {
    display: flex; align-items: flex-start; justify-content: space-between;
    padding-bottom: 24px; border-bottom: 2px solid #101012;
  }
  .brand { font-size: 26px; font-weight: 800; letter-spacing: 0.18em; }
  .brand small {
    display: block; font-size: 10px; font-weight: 700; letter-spacing: 0.08em;
    color: #66666c; margin-top: 4px; text-transform: uppercase;
  }
  .doc { text-align: right; }
  .doc h1 { font-size: 20px; font-weight: 800; letter-spacing: -0.01em; }
  .doc .status {
    display: inline-block; margin-top: 6px; padding: 4px 12px;
    border-radius: 999px; background: rgba(30, 122, 70, 0.12); color: #1e7a46;
    font-size: 10.5px; font-weight: 800; letter-spacing: 0.06em; text-transform: uppercase;
  }
  .meta { margin-top: 28px; }
  .row {
    display: flex; justify-content: space-between; gap: 24px;
    padding: 9px 0; border-bottom: 1px solid #ececea; font-size: 12.5px;
  }
  .row .k { color: #66666c; font-weight: 600; }
  .row .v { font-weight: 700; text-align: right; }
  table { width: 100%; margin-top: 32px; border-collapse: collapse; font-size: 12.5px; }
  th {
    text-align: left; font-size: 10.5px; font-weight: 800; letter-spacing: 0.06em;
    text-transform: uppercase; color: #66666c; padding: 0 0 10px;
    border-bottom: 2px solid #101012;
  }
  th:last-child, td:last-child { text-align: right; }
  td { padding: 14px 0; border-bottom: 1px solid #ececea; font-weight: 600; }
  td b { font-weight: 800; }
  td .tag { color: #66666c; font-size: 11px; font-weight: 700; }
  .total {
    display: flex; justify-content: flex-end; gap: 40px; margin-top: 18px;
    font-size: 15px; font-weight: 800;
  }
  .foot {
    margin-top: 56px; padding-top: 16px; border-top: 1px solid #ececea;
    font-size: 10.5px; color: #66666c; font-weight: 600; line-height: 1.6;
  }
  @media print { body { padding: 24px; } }
</style>
</head>
<body>
  <div class="sheet">
    <div class="head">
      <div class="brand">AXZY<small>Digital Asset Store</small></div>
      <div class="doc">
        <h1>Invoice</h1>
        <span class="status">Paid</span>
      </div>
    </div>

    <div class="meta">${rows}</div>

    <table>
      <thead>
        <tr><th>Item</th><th>Qty</th><th>Amount</th></tr>
      </thead>
      <tbody>
        <tr>
          <td><b>${esc(inv.product)}</b><br /><span class="tag">${esc(inv.tag)} · one-time license</span></td>
          <td>1</td>
          <td>$${inv.price.toFixed(2)}</td>
        </tr>
      </tbody>
    </table>

    <div class="total"><span>Total paid</span><span>$${inv.price.toFixed(2)}</span></div>

    <div class="foot">
      Thank you for your purchase. This invoice was generated by AXZY Store —
      for questions contact hello@axzy.store or join discord.gg/axzy.<br />
      Licenses are delivered digitally to your profile and remain available for re-download.
    </div>
  </div>
</body>
</html>`;
}

/* open the invoice in a new tab and trigger the print dialog —
   the user can print it or pick "Save as PDF" from there */
export function printInvoice(inv: InvoiceData) {
  const win = window.open("", "_blank", "width=760,height=900");
  if (!win) return;
  win.document.write(invoiceHtml(inv));
  win.document.close();
  win.focus();
  // give the new document a beat to layout before opening the dialog
  setTimeout(() => win.print(), 350);
}
